ARG IMAGE_TAG
FROM slurm-docker-cluster:${IMAGE_TAG}

RUN dnf -y install openssh-server openssh-clients; \
    sed -i 's/^\(UsePAM yes\)/# \1/' /etc/ssh/sshd_config; \
    ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '' && \
    ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' && \
    ssh-keygen -t dsa -f /etc/ssh/ssh_host_ed25519_key  -N ''; \
    dnf clean all;

EXPOSE 22

ARG ROOT_PASSWORD
ENV ROOT_PASSWORD=${ROOT_PASSWORD}

CMD ["login"]
